mutation CreatePlaygroundUnit($input: CreatePlaygroundUnitInput!) {
  createPlaygroundUnit(input: $input) {
    id
  }
}

mutation BulkCreatePlaygroundUnits($input: BulkCreatePlaygroundUnitInput!) {
  bulkCreatePlaygroundUnits(input: $input)
}
